name: Update content submodule

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.VAULT_SSH_KEY }}

      - name: Add submodule
        run: |
          git config --global user.email "nish.professional@gmail.com"
          git config --global user.name "Nishanth-Gobi"
          git submodule add git@github.com:Nishanth-Gobi/Obsidian-Vault.git content
          cd content
          ls
          git commit -m "Update content"
          git push

        env:
          SSH_PRIVATE_KEY: ${{ secrets.VAULT_SSH_KEY }}
  call-deploy-workflow:
    needs: [ update-content ]
    uses: ./.github/workflows/deploy.yml
