name: Update content submodule

on:
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.VAULT_SSH_KEY }}

      - name: Update submodule
        run: |
          git config --global user.email "nish.professional@gmail.com"
          git config --global user.name "Nishanth-Gobi"
          git submodule update --remote content
          git add --all
          git commit -m "Update submodule"
          git push origin ${GITHUB_REF##*/}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VAULT_SSH_KEY }}
  call-deploy-workflow:
    uses: ./.github/workflows/deploy.yml
