name: Update content submodule

on:
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.VAULT_SSH_KEY }}

      - name: Add submodule
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VAULT_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "nish.professional@gmail.com"
          git config --global user.name "Nishanth-Gobi"
          git submodule update --remote --merge
          git add --all
          git commit -m "Update content"
          git push
        
  call-deploy-workflow:
    needs: [ update-content ]
    uses: ./.github/workflows/deploy.yml


# git submodule add git@github.com:Nishanth-Gobi/Obsidian-Vault.git content