name: Update content submodule

on:
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive
          ssh-key: ${{ secrets.VAULT_SSH_KEY }}

      - name: Update submodule
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          git submodule update --init --remote --rebase content

      - name: Commit and push changes
        run: |
          git add content
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "chore: update content submodule"
            git push
          else
            echo "No changes to commit."
          fi
