name: Update content submodule

on:
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.VAULT_SSH_KEY }}

      - name: Add submodule
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VAULT_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod +x ./.github/workflows/update_submodule.sh
          ./.github/workflows/update_submodule.sh
