name: Daily update of content submodule

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.VAULT_SSH_KEY }}

      - name: Update submodule
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VAULT_SSH_KEY }}
     
      - name: Commit
        run:
          git config --global user.email "nish.professional@gmail.com"
          git config --global user.name "Nishanth-Gobi"
          git add --all
          git commit -m "Update submodule" || echo "No changes to commit" 
          git push
