name: Daily update of content submodule

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code including submodules
        uses: actions/checkout@v4

      - name: Update submodule
        run: |
          git config --global user.email "nish.professional@gmail.com"
          git config --global user.name "Nishanth-Gobi"
          git submodule update --remote --merge
          git commit --allow-empty -am "Update submodule" 
          git push origin HEAD:main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VAULT_SSH_KEY }}
