name: Daily update of content submodule

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  run-daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.VAULT_SSH_KEY }}

      - name: Update submodule
        run: |
          git config user.email "nish.professional@gmail.com"
          git config user.name "Nishanth-Gobi"
          git submodule update --remote content
          git commit --allow-empty -am "Update submodule" 
          git push
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VAULT_SSH_KEY }}
